name: build

on:
  - workflow_dispatch
  - push

jobs:
  build_wheel:
    name: wheels-${{ matrix.os}}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: macos-latest
            arch: arm64
          - os: macos-latest
            arch: x86_64
          - os: windows-latest
            arch: AMD64

    steps:
      - uses: actions/checkout@v4

      - name: Clone PySCIPOpt
        run: git clone https://github.com/scipopt/PySCIPOpt.git

      - uses: pypa/cibuildwheel@v2.21.1
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest tests"
          CIBW_MANYLINUX_*_IMAGE: manylinux_2_28

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os}}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl
